version: '3'

services:
  postgresql:
    build: ./docker-compose/postgresql
    volumes:
      - ${VOLUME_PATH}/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
  confluence:
    build: ./docker-compose/confluence
    volumes:
      - ${VOLUME_PATH}/confluence:/var/atlassian/application-data/confluence
    ports:
      - ${CONFLUENCE_PORT}:8090
      - 8091:8091
    environment:
      - JVM_MINIMUM_MEMORY=${CONFLUENCE_JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${CONFLUENCE_JVM_MAXIMUM_MEMORY}
      - ATL_JDBC_URL=jdbc:postgresql://postgresql:5432/atlassian_confluence?useSSL=false
      - ATL_JDBC_USER=postgres
      - ATL_JDBC_PASSWORD=1234
      - ATL_DB_TYPE=postgresql
    depends_on:
      - jira
  jira:
    build: ./docker-compose/jira
    volumes:
      - ${VOLUME_PATH}/jira:/var/atlassian/application-data/jira
    ports:
      - ${JIRA_PORT}:8080
    environment:
      - JVM_MINIMUM_MEMORY=${JIRA_JVM_MINIMUM_MEMORY}
      - JVM_MAXIMUM_MEMORY=${JIRA_JVM_MAXIMUM_MEMORY}
    depends_on:
      - postgresql
